---

  - name: install dependencies
    become: yes
    apt: 
      name: python3-exif
      state: present
  
  # following FHS
  - name: ensure installation directorys
    become: yes
    file:
      name: '{{ item }}'
      mode: '0755'
      state: 'directory'
    with_items: 
      - '/opt/photo_mover'
      - '/etc/opt/photo_mover'

  - name: ensure log directory
    become: yes
    file:
      name: '/var/log/photo_mover'
      mode: '0755'
      state: 'directory'
      user: {{ photo_mover_user }}
      group: {{ photo_mover_group }}

  - name: copy python script
    become: yes
    copy:
      src: 'move_photos.py'
      dest: '/opt/photo_mover/move_photos.py'
      mode: '0755'

  - name: create source list
    become: yes
    template: 
      src: 'sources.j2' 
      dest: '/etc/opt/photo_mover/sources' 
      mode: '0755'

  - name: create script
    become: yes
    template: 
      src: 'photo_mover.sh.j2' 
      dest: '/opt/photo_mover/photo_mover.sh' 
      mode: '0755'