---

  # move photos on schedule
    
  - name: create service descriptor for scheduled move
    become: yes
    template: 
      src: 'photo_mover.service.j2' 
      dest: '/etc/systemd/system/photo_mover.service' 
      mode: '0644'
    notify: restart photo_mover.service
  - name: create timer descriptor for scheduled move
    become: yes
    template: 
      src: 'photo_mover.timer.j2' 
      dest: '/etc/systemd/system/photo_mover.timer' 
      mode: '0644'
    notify: restart photo_mover.timer
  - name: enable schedule timer descriptor
    become: yes
    systemd: 
      name: 'photo_mover.timer' 
      enabled: 'yes'
      state: 'started'